name: rl_tutorials
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=2.114=mkl
  - blas-devel=3.9.0=14_win64_mkl
  - brotlipy=0.7.0=py37hcc03f2d_1004
  - ca-certificates=2022.5.18.1=h5b45459_0
  - certifi=2022.5.18.1=py37h03978a9_0
  - cffi=1.15.0=py37hd8e9650_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=37.0.1=py37h21b164f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - debugpy=1.6.0=py37hf2a7229_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - freetype=2.10.4=h546665d_1
  - idna=3.3=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h57928b3_3787
  - ipykernel=6.13.0=py37h90c5f73_0
  - jedi=0.18.1=py37h03978a9_1
  - jpeg=9e=h8ffe710_1
  - jupyter_client=7.3.1=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py37h03978a9_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=14_win64_mkl
  - libcblas=3.9.0=14_win64_mkl
  - libdeflate=1.10=h8ffe710_0
  - liblapack=3.9.0=14_win64_mkl
  - liblapacke=3.9.0=14_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.3.0=hc4061b1_4
  - libuv=1.43.0=h8ffe710_0
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.11=h8ffe710_1014
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2022.0.0=h0e2418a_796
  - mkl-devel=2022.0.0=h57928b3_797
  - mkl-include=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - numpy=1.21.6=py37h2830a78_0
  - openjpeg=2.4.0=hb211442_1
  - openssl=3.0.3=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py37h8675073_0
  - pip=22.1.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - psutil=5.9.1=py37hcc03f2d_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h03978a9_5
  - python=3.7.12=h900ac77_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.11.0=py3.7_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pywin32=303=py37hcc03f2d_0
  - pyzmq=23.0.0=py37hcce574b_0
  - requests=2.27.1=pyhd8ed1ab_0
  - setuptools=62.3.2=py37h03978a9_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.5=h8ffe710_0
  - tbb=2021.5.0=h2d74725_1
  - tk=8.6.12=h8ffe710_0
  - torchaudio=0.11.0=py37_cu113
  - torchvision=0.12.0=py37_cu113
  - tornado=6.1=py37hcc03f2d_3
  - typing_extensions=4.2.0=pyha770c72_1
  - ucrt=10.0.20348.0=h57928b3_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py37h03978a9_4
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_1
  - zlib=1.2.11=h8ffe710_1014
  - zstd=1.5.2=h6255e5f_1
  - pip:
    - cloudpickle==2.1.0
    - cycler==0.11.0
    - dill==0.3.4
    - easydict==1.9
    - fonttools==4.33.2
    - gym==0.21.0
    - importlib-metadata==4.12.0
    - ipython==7.32.0
    - kiwisolver==1.4.2
    - matplotlib==3.5.1
    - pandas==1.3.5
    - pygments==2.11.2
    - pyparsing==3.0.8
    - pytz==2022.1
    - scipy==1.7.3
    - seaborn==0.11.2
    - traitlets==5.1.1
    - zipp==3.8.1
prefix: C:\Users\24438\anaconda3\envs\rl_tutorials
