general_cfg:
  algo_name: PER_DQN
  device: cuda
  env_name: CartPole-v1
  mode: train
  load_checkpoint: false
  load_path: Train_CartPole-v1_PER_DQN_20221026-054757
  max_steps: 200
  save_fig: true
  seed: 0
  show_fig: false
  test_eps: 10
  train_eps: 200
algo_cfg:
  batch_size: 64
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.95
  lr: 0.0001
  target_update: 4
