general_cfg:
  algo_name: QLearning
  device: cpu
  env_name: FrozenLakeNoSlippery-v1
  mode: test
  load_checkpoint: true
  load_path: Train_FrozenLakeNoSlippery-v1_QLearning_20221030-014504
  max_steps: 200
  save_fig: true
  seed: 10
  show_fig: false
  test_eps: 20
  train_eps: 800
algo_cfg:
  epsilon_decay: 2000
  epsilon_end: 0.1
  epsilon_start: 0.7
  gamma: 0.95
  lr: 0.9
