general_cfg:
  algo_name: A2C
  device: cuda
  env_name: CartPole-v1
  mode: train
  load_checkpoint: false
  load_path: Train_CartPole-v1_DQN_20221026-054757
  max_steps: 200
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 20
  train_eps: 600
algo_cfg:
  continuous: false
  batch_size: 64
  buffer_size: 100000
  gamma: 0.0003
  lr: 0.001
